djangoblog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.Register_View.as_view(), name='signup'),
    path('login/', views.Login_view.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from accounts import views
#from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('rss/', include('rssapp.urls')),
    re_path(r'^$', views.home_view, name='homes'),
    #path('about/', views.about),
    #path('', views.home),
]

djangoblog/rssapp/urls.py
from django.urls import path
from . import views

app_name = 'rssapp'

urlpatterns = [
    path('user/', views.rss_view, name='rssapp'),
    path('api/', views.ApiRssFeedAdmin.as_view(), name='api'),
    path('api/update/', views.ApiRssFeedRetrieve.as_view(), name='api2'),
    path('adding/', views.rss_add, name='add'),
]

djangoblog/accounts/models.py
from django.db import models

# Create your models here.

djangoblog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .serializers import User_Serializers, Userlog_Serializers
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth import authenticate, login
# Create your views here.


def home_view(request):
    if request.user.is_authenticated:
        return redirect('/rss/user')
    return render(request, 'accounts/home.html')


class Login_view(GenericAPIView):
    serializer_class = Userlog_Serializers

    def post(self, request):
        #form = AuthenticationForm(data=request.POST)
        serializer = self.serializer_class(data=request.data,
                                           request=request)

        if serializer.is_valid():
            login(request,
                  serializer.user_cache,
                  backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/rss/user')
        return render(request, 'accounts/login.html', {'status': serializer.errors})

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('/rss/user')
        return render(request, 'accounts/login.html')


class Register_View(GenericAPIView):
    serializer_class = User_Serializers

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('/rss/user')
        return render(request, 'accounts/signup.html')

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            username = serializer.validated_data.get("username")
            password = serializer.validated_data.get("password")
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('/rss/user')
            # return Response(serializer.data, status=status.HTTP_201_CREATED)
        # print(serializer.errors)
        return render(request, 'accounts/signup.html', {'status': serializer.errors})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

djangoblog/accounts/templates/accounts/home.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}

<div class="card text-center bg.">

    <div class="card-body">
        <h2 class="card-title ">Welcome</h2>
        <p class="card-text">RSS demo app</p>
        <div class="p-2">
            <a href="/accounts/login/" class="btn btn-primary">LogIn</a>
        </div>
        <div>
            <a href="/accounts/signup/" class="btn btn-success">SignUp</a>
        </div>

    </div>

</div>

{% endblock content %}

djangoblog/accounts/templates/accounts/login.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}

<center>
    <div class="card text-center px-4 m-4" style="max-width: 30rem;" id="create-card">

        <div class="card-body">
            <h2 class="card-title">Login</h2>
            <form action="{% url 'accounts:login' %}" method="post" id="signup_user">
                {% csrf_token %}

                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username"
                        placeholder="Enter your Username" autofocus required autocapitalize="none">
                    <small id="usernamehelp" class="form-text text-muted">Please put your username </small>
                </div>
                {% for error in status.username %}
                <h6 class="text-danger">{{ error }}</h6>
                {% endfor %}

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password" minlength="8" required>
                    <small id="passwordhelp" class="form-text text-muted">Please put your password</small>
                </div>

                {% for error in status.password %}
                <h6 class="text-danger">{{ error }}</h6>
                {% endfor %}
                {% for error in status.non_field_errors %}
                <h6 class="text-danger">{{ error }}</h6>
                {% endfor %}
                <!-- <input type="submit" value="Submit" class="btn-primary"> -->
                <button type="submit" value="Submit" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z" />
                        <path fill-rule="evenodd"
                            d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                    </svg> Login </button>
            </form>


        </div>
        <!-- <center>
        <div class="spinner-border text-primary my-2" role="status" id="spinner-add" style="display: none;">
            <span class="visually-hidden"></span>
        </div>
    </center> -->

    </div>

</center>
{% endblock content %}

djangoblog/accounts/templates/accounts/signup.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}

<center>
    <div class="card text-center px-4 m-4" style="max-width: 30rem;" id="create-card">

        <div class="card-body">
            <h2 class="card-title">Create your account</h2>
            <form action="/accounts/signup/" method="post" id="signup_user">
                {% csrf_token %}

                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username"
                        placeholder="Enter your Username" autofocus required autocapitalize="none">
                    <small id="usernamehelp" class="form-text text-muted">Please put your user name.Required. 150
                        characters or fewer. Letters, digits and @/./+/-/_ only. </small>
                </div>
                {% for error in status.username %}
                <h6 class="text-danger">{{ error }}</h6>
                {% endfor %}
                <div class="form-group">
                    <label for="first_name">First name</label>
                    <input type="text" name="first_name" class="form-control" id="first_name" required
                        placeholder="First name">
                    <small id="firstnamehelp" class="form-text text-muted">Please put your first name </small>
                </div>
                <div class="form-group">
                    <label for="last_name">Last name</label>
                    <input type="text" name="last_name" class="form-control" id="last_name" required
                        placeholder="Last name">
                    <small id="lastnamehelp" class="form-text text-muted">Please put your last name </small>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="form-control" id="email" required placeholder="Email@">
                    <small id="emailhelp" class="form-text text-muted">Please put your email @ </small>
                </div>
                {% for error in status.email %}
                <h6 class="text-danger">{{ error }}</h6>
                {% endfor %}
                <div class="form-group">
                    <label for="password_1">Password</label>
                    <input type="password" name="password_1" class="form-control" id="password_1" minlength="8"
                        required>
                    <small id="passwordhelp" class="form-text text-muted">At least 8 caracters</small>
                </div>
                <div class="form-group">
                    <label for="password_2">Confirm the password</label>
                    <input type="password" name="password_2" class="form-control" id="password_2" minlength="8"
                        required>
                    <small id="password2help" class="form-text text-muted">Please repeat the password</small>
                </div>
                {% for error in status.password %}
                <h6 class="text-danger">{{ error }}</h6>
                {% endfor %}
                {% for error in status.non_field_errors %}
                <h6 class="text-danger">{{ error }}</h6>
                {% endfor %}
                <!-- <input type="submit" value="Submit" class="btn-primary"> -->
                <button type="submit" value="Submit" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z" />
                        <path fill-rule="evenodd"
                            d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                    </svg> Signup </button>
            </form>


        </div>
        <!-- <center>
        <div class="spinner-border text-primary my-2" role="status" id="spinner-add" style="display: none;">
            <span class="visually-hidden"></span>
        </div>
    </center> -->

    </div>

</center>

{% endblock content %}