djangoblog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.Register_View.as_view(), name='signup'),
    path('login/', views.Login_view.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from accounts import views
#from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('rss/', include('rssapp.urls')),
    re_path(r'^$', views.home_view, name='homes'),
    #path('about/', views.about),
    #path('', views.home),
]

djangoblog/rssapp/urls.py
from django.urls import path
from . import views

app_name = 'rssapp'

urlpatterns = [
    path('user/', views.rss_view, name='rssapp'),
    path('api/', views.ApiRssFeedAdmin.as_view(), name='api'),
    path('api/update/', views.ApiRssFeedRetrieve.as_view(), name='api2'),
    path('adding/', views.rss_add, name='add'),
]

djangoblog/accounts/models.py
from django.db import models

# Create your models here.

djangoblog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .serializers import User_Serializers, Userlog_Serializers
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth import authenticate, login
# Create your views here.


def home_view(request):
    if request.user.is_authenticated:
        return redirect('/rss/user')
    return render(request, 'accounts/home.html')


class Login_view(GenericAPIView):
    serializer_class = Userlog_Serializers

    def post(self, request):
        #form = AuthenticationForm(data=request.POST)
        serializer = self.serializer_class(data=request.data,
                                           request=request)

        if serializer.is_valid():
            login(request,
                  serializer.user_cache,
                  backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/rss/user')
        return render(request, 'accounts/login.html', {'status': serializer.errors})

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('/rss/user')
        return render(request, 'accounts/login.html')


class Register_View(GenericAPIView):
    serializer_class = User_Serializers

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('/rss/user')
        return render(request, 'accounts/signup.html')

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            username = serializer.validated_data.get("username")
            password = serializer.validated_data.get("password")
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('/rss/user')
            # return Response(serializer.data, status=status.HTTP_201_CREATED)
        # print(serializer.errors)
        return render(request, 'accounts/signup.html', {'status': serializer.errors})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

djangoblog/accounts/templates/accounts/layout/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static "accounts/css/bootstrap.min.css" %}">

    <title>Django Blog</title>
</head>

<body class="container mt-5 bg-dark ">
    {%include "./navbar.html" %}
    <nav class="mb-3">
        {% if user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-primary btn-sm" type="submit">Log Out</button>
        </form>
        {% endif %}
    </nav>
    {% block content %}

    {% endblock content %}
</body>

</html>

djangoblog/accounts/templates/accounts/layout/navbar.html
<html>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Demo RSS app</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary btn-sm" type="submit">Log Out</button>
                </form>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>

</html>